;	This file containts language of the panel. 
;	ENGLISH (BASIC)

[Variables]

;-----------
;	Main
;-----------

M_I=Installation of Ashuramaru Bundle was successfull.
M_Desc=Click start to begin setting up this suite.
M_Ty=Thank you for downloading my suit skin for rainmeter! ~Kurou
M_S=Start

;-----------
;	Popups
;-----------

;	MSIAfterburner

MSI_Title=WARNING!
MSI_Desc=MSIAfterburner is not being detected in background processes! Turn it ON becouse Statistics skin will not work without it!

;	HWInfo

HW_Title=WARNING!
HW_Desc=HWInfo is not being detected in background processes! Turn it ON becouse Statistics skin will not work without it!

;	Uninstall

U_Title=Uninstall Warning
U_Desc=Are you sure you want to uninstall Ashuramaru Bundle skin from your pc?
U_Uninstall=Uninstall

;-----------
;	Panel
;-----------

SB_Appearance=Appearance
SB_Welcome=Welcome
SB_Settings=Settings
SB_Update=Update
SB_Skins=Skins
SB_Wiki=Wiki
SB_Authors=Authors
SB_Change_Log=Change Log
A_B=Appearance
P_C=Cancel
P_S=Skins
P_P=Page
P_ToolTipText=Visit creative commons website to view license

;	Welcome

W_Title=Welcome in panel
W_Desc=Ashuramaru Bundle is a skin suite designed to connect every supported skin with the custome panel made by Kurou to have as much customization possible withing this system. Every skin was modified and connected with the panel to give a no expierienced users easy way to change default looking skin to their own imagination within limitations of the panel.
W_LB_3=Website
W_LB_4=Forum

;	Appearance

A_Desc=General visual options across all skins
A_C_Desc=Here you can customize all colors that appear in any skin in this bundle.
A_F_Desc=Here you can change font in individual parts of the skin
A_C_Panel_Title=Panel Colors
A_C_Illustro_Title=Illustro Colors
A_C_Other_Title=Other Colors
A_C_P_ToolTipText=Headers
A_C_S_ToolTipText=Descriptions
A_C_T_ToolTipText=Titles
A_C_Q_ToolTipText=Texts
A_C_Qu_ToolTipText=Links
A_C_Sr_ToolTipText=Buttons
A_C_Se_ToolTipText=Sidebar
A_C_IP_ToolTipText=Headers
A_C_IS_ToolTipText=Label Names
A_C_IT_ToolTipText=Values
A_C_IQ_ToolTipText=Bars
A_C_IQu_ToolTipText=Clock Values
A_C_ISr_ToolTipText=Graphs
A_C_ISe_ToolTipText=Seperators
A_C_OP_ToolTipText=VectorCopy Bars
A_C_OS_ToolTipText=Panel Background
A_C_Default_Colors=Default Colors
A_BG_Title=Background Type
A_BG_ToolTipText=Classic Background from illustro
A_BG_ToolTipText2=Improved classic illustro background
A_BG_ToolTipText3=Recolored Modern background with rounded edges
A_BG_ToolTipText4=Background with maxiumum opacity
A_BG_ToolTipText5=Opacity background with blur effect
A_BG_ToolTipText6=Acrylic effect behind opacity background
A_BG_ToolTipText7=Redesigned default illustro background
A_BG_ToolTipText8=For those who are on the light side of power
A_BG_Classic=Classic Background
A_BG_Modern=Modern Background
A_BG_Rounded=Rounded Background
A_BG_Opaque=Opaque Background
A_BG_Blurred=Blurred Background
A_BG_Acrylic=Acrylic Background
A_BG_Definitive=Definitive Background
A_BG_Light=Light Background
A_Wall_Title=Set Wallpaper
A_Wall_TooltTipTextTitle=Wallpaper
A_Wall_ToolTipText=Set this wallpaper
A_Change_Colors=Change Colors
A_Change_Fonts=Change Fonts
A_C_Presets=Preset
A_C_Presets_ToolTipText=LMB > Load | RMB > Save | SCR > Reset
A_F_Title=Change Fonts
A_F_P_Title=Panel Font
A_F_I_Title=Illustro Font
A_F_FC_Title=Chose Font
A_F_DF=Default Fonts

;	Settings

S_Desc=Main settings page for skin adjustments.
S_Panel=Panel Settings
S_Statistics=Statistics Settings
S_Taskbar=Translucent Taskbar Settings
S_TaskbarX=TaskbarX Settings
S_VectorCopy=VectorCopy Settings
S_Processes=Processes Settings
S_CyberSearch=CyberSearch Settings
S_Dock=Dock Settings
S_Clock=Clock Settings
S_Uninstall=Uninstall
S_Usage=Usage Monitor

;	Uninstall

S_U_Title=Removing the Ashuramaru Bundle
S_U_Desc=Click the button to remove this bundle from your pc!

;	Panel Settings

S_P_Desc=Here you can adjust settings of the panel
S_P_Language_Title=Language
S_P_L_EN=English
S_P_L_PL=Polish
S_P_Automatic_Game_Mode=Automatic Game Mode
S_P_AGM_Clock=Clock
S_P_AGM_Battery=Battery
S_P_AGM_Recycle_Bin=Recycle Bin
S_P_AGM_Dock=Dock
S_P_AGM_Notes=Notes
S_P_Tray=Tray Icon
S_P_PM=Automatic Performance Monitor
S_P_Q=Panel Quality
S_P_Q_L=Low
S_P_Q_M=Medium
S_P_Q_H=High
S_P_N=Notifications
S_P_L=Logs
S_P_L_OL=Open Logs

;	Statistics Settings

S_S_Desc=Here you can adjust settings of the Statistics skin
S_S_Title=Statistics Variation
S_S_Combined=Combined
S_S_Individual=Individual
S_S_Minimal=Minimal
S_S_ToolTipTextTitle=Combined Statistics
S_S_ToolTipTextTitle2=Individual Statistics
S_S_ToolTipTextTitle3=Minimal Statistics
S_S_ToolTipText=Original form of Statistics skin
S_S_ToolTipText2=Seperates Statistics skin to 3 different parts
S_S_ToolTipText3=Minimal version of the skin
S_S_C_Variation=Statistics Combined Variation
S_S_C_ToolTipText=Works only in Combined variation
S_S_C_ToolTipText2=Turns on network and turns off System and Disks parts of the skin
S_S_C_ToolTipText3=Turns on network and system and turns off Disks part of the skin
S_S_C_ToolTipText4=Turns on all parts of the skin
S_S_C_Network_Only=Network Only
S_S_C_Network_System=Network + System
S_S_C_Network_System_Disks=Network+System+Disks
S_S_S_Title2=Statistics Detailed
S_S_S_CPU=Processor
S_S_S_GPU=Graphics
S_S_S_WEB=Network
S_S_S_RAM=Memory
S_S_S_DISK=Drives
S_S_S_DL_Title=Statistics Disk Letters
S_S_S_D_Title=Statistics Disks
S_S_S_D_Disk=Disk
S_S_S_D_ToolTipText=Click to toggle disk
S_S_L_Title=Statistics Labels
S_S_L_Network_Label=Network
S_S_L_Network=Latency
S_S_L_Network2=Upload
S_S_L_Network3=Download
S_S_L_Network4=Traffic
S_S_L_Network5=Speed
S_S_L_System_Label=System
S_S_L_System=CPU Usage
S_S_L_System2=CPU Clock
S_S_L_System3=CPU Temperature
S_S_L_System4=GPU Usage
S_S_L_System5=GPU Clock
S_S_L_System6=GPU Memory Clock
S_S_L_System7=GPU Voltage
S_S_L_System8=GPU Temperature
S_S_L_System9=GPU Fan Speed
S_S_L_System10=RAM Usage
S_S_L_System11=SWAP Usage
S_S_L_System12=GPU Memory Usage
S_S_L_System12.5=GPU Memory Usage Percentage
S_S_L_System13=GPU Fan Speed RPM
S_S_PH_Title=Ping Host
S_S_GMM_Title=GPU Max Memory
S_S_NTL_Title=Network Traffic Limit
S_S_ME_Title=Statistics Measures Engine
S_S_ME_MSIAfterburner=MSIAfterburner
S_S_ME_HWInfo=HWInfo64
S_S_SDT_Title=Statistics Disks Type
S_S_SDT_Classic=Classic
S_S_SDT_Advanced=Advanced

;	Translucent Taskbar Settings

S_T_Desc=Here you can adjust settings of the Translucent skin
S_T_Title=Translucent Taskbar Variation
S_T_Blurred=Blurred
S_T_UnBlurred=Unblurred
S_T_ToolTipText=Toggle taskbar effect

;	VectorCopy Settings

S_V_Desc=Here you can adjust settings of the VectorCopy skin
S_V_Title=VectorCopy Variation
S_V_ToolTipText=Toggle VectorCopy visualizer style

;	Processes Settings

S_PR_Desc=Here you can adjust processes skin
S_PR_Title=Processes Variations
S_PR_Combined=Combined
S_PR_ToolTipText=All in one
S_PR_ToolTipText2=Individual parts
S_PR_Individual=Individual
S_PR_Graph=Show Graphs

;	Dock Settings

S_D_Desc=Here you can change settings of the dock skin
S_D_Title=Add Program
S_D_Title2=Add Icon
S_D_ToolTipTextTitle=Executable
S_D_ToolTipText=To add executable to dock you need to enter full path to it in input box after clicking ADD button
S_D_Add=ADD
S_D_NOT_DEFINED=NOT DEFINED
S_D_I_ToolTipTextTitle=Icon
S_D_I_ToolTipText=To add icon type image name without extension on the end after clicking ADD button
S_D_I_Amount=Icons Amount
S_D_I_A_ToolTipText=Chose how many icons you want in dock
S_D_I=ICONS
S_D_Apply=Apply Settings
S_D_I_Folder=ICONS FOLDER

;	CyberSearch Settings

S_CS_Desc=Here you can adjust CyberSearch skin
S_CS_Title=Search Engine
S_CS_Google_ToolTipText=Standard web search engine
S_CS_Reddit_ToolTipText=Web engine for website Reddit
S_CS_YouTube_ToolTipText=Vide streaming service search engine
S_CS_DuckDuckGo_ToolTipText=One of the most secure and anonymous search engine
S_CS_Bing_ToolTipText=Search engine developed by microsoft

;	TaskbarX Settings

S_TX_Desc=Here you can adjust TaskbarX settings
S_TX_Title=TaskbarX Variation
S_TX_Transparent=Transparent
S_TX_Blurred=Blurred
S_TX_Acrylic=Acrylic
S_TX_Transparent_Gradient=Transparent Gradient
S_TX_Opaque=Opaque
S_TX_Title2=Pause when in fullscreen
S_TX_Title3=Centering Icons
S_TX_Title4=Show Tray Icon
S_TX_Title5=Transform into segments
S_TX_Title6=Animation Style
S_TX_Title7=Color Gradient Opacity
S_TX_AS_Chosen=Chosen
S_TX_AS_None=None
S_TX_AS_Linear=Linear

;	Clock Settings

S_CL_Desc=Here you can adjust settings of the clock skin
S_CL_Title=Clock Timer
S_CL_Hour=Hour
S_CL_ToolTipText=Europe Measuring
S_CL_ToolTipText2=English Measuring
S_CL_Title2=Clock Features
S_CL_CF_Date_Info=Date Info
S_CL_CF_ToolTipText=Show Date
S_CL_CF_Year_Info=Year Info

;	Update

U_Current_Version=Current Version
U_Download=Download
U_CFU=CHECK FOR UPDATES
U_Connecting=Checking for updates...
U_UpToDate=Using up to date version
U_Update=is available for download!
U_Dev=Using development version

;	Skins

SK_Desc=Chose which skins you want to use
SK_ON=ON
SK_OFF=OFF
SK_View=VIEW
SK_Statistics=Statistics
SK_Processes=Processes
SK_Battery=Battery
SK_Recycle_Bin=Recycle Bin
SK_Hardware_Info=Hardware Info
SK_Dock=Dock
SK_Notes=Notes
SK_Clock=Clock
SK_VolumeControl=Volume Control
SK_SystemControl=System Control
SK_Clipboard=Clipboard

;-----------
;	Supported Skins
;-----------

;	Clock

SS_C_Day=Day
SS_C_Week=Week
SS_C_Quarter=Quarter

;	Battery

SS_B_Title=Battery
SS_B_Level=Battery Level
SS_B_Left=Left

;	Recycle Bin

SS_RB_Title=Recycle Bin
SS_RB_Items=Items
SS_RB_ToolTipText=Click to empty bin
SS_RB_ToolTipText2=Click to open bin

;	Statistics

SS_S_N_Title=Network
SS_S_N_Latency=Latency
SS_S_N_Upload=Upload
SS_S_N_Download=Download
SS_S_N_Speed=Speed
SS_S_N_Traffic=Traffic
SS_S_S_Title=System
SS_S_S_CPU_U=CPU Usage
SS_S_S_CPU_T=CPU Temperature
SS_S_S_CPU_C=CPU Clock
SS_S_S_GPU_U=GPU Usage
SS_S_S_GPU_T=GPU Temperature
SS_S_S_GPU_C=GPU Core Clock
SS_S_S_GPU_M=GPU Memory Clock
SS_S_S_GPU_M2=GPU Memory Usage
SS_S_S_GPU_V=GPU Voltage
SS_S_S_GPU_FS=GPU Fan Speed
SS_S_S_RAM=RAM Usage
SS_S_S_SWAP=SWAP Usage
SS_S_D_Title=Disks
SS_S_D_Used=used

;	Statistics Detailed

SD_D_Title=Drives
SS_D_Drive=Drive
SD_D_Used=Used
SD_D_Total=Total
SD_D_Read=Read
SD_D_Write=Write
SD_D_Activity=Activity
SD_G_Title=Graphics
SD_G_Core_Clock=Core Clock
SD_G_Memory_Clock=Memory Clock
SD_G_Power=Power
SD_G_Temperature=Temperature
SD_G_Load=Load
SD_G_Fan_Speed=Fan Speed
SD_G_Memory=Memory
SD_M_Title=Memory
SD_M_Used=Used
SD_M_Free=Free
SD_N_Title=Network
SD_N_External=External
SD_N_Internal=Internal
SD_N_Total=Total
SD_N_Latency=Latency
SD_N_Upload=Upload
SD_N_Download=Download
SD_P_Title=Processor
SD_P_Core_Clock=Core Clock
SD_P_Temperature=Temperature
SD_P_Handle_Count=Handle Count
SD_P_Thread_Count=Thread Count
SD_P_Uptime=Uptime
SD_P_Total_Usage=Total Usage

;	Processes

SS_PR_Title=Top CPU Processes
SS_PR_Title2=Top GPU Processes
SS_PR_Title3=Top IO Processes
SS_PR_Title4=Top RAM Processes
SS_PR_ToolTipTextTitle=Top Processes
SS_PR_ToolTipText=Use SCRUP and SCRDOWN to change config

;	Hardware Info

SS_HI_Title=Hardware Info
SS_HI_Motherboard=Motherboard
SS_HI_Sound_Devices=Sound Devices
SS_HI_Network_Adapters=Network Adapters

;	Dock

SS_D_ToolTipTextTitle=Icon Shortcut
SS_D_ToolTipText=LMB > Open | SRC > Reset

;	Volume Control

V_C_Title=Volume Control
V_OM=Open Mixer
V_ND=Next Device
V_PD=Previous Device
V_D=Volume Down
V_U=Volume Up
V_TM=Toggle Mute

;	Notifications

N_Title=New update available!
N_Desc=Check Update tab in panel for more info!
N_Title2=Closing Panel
N_Desc2=Panel has been closed, you can open it via tray icon or rainmeter!
N_Title3=An Error Accured
N_Desc3=Error Code
N_Title4=Notifications enabled!
N_Desc4=Now Notifications will show every time certain events happen!
N_Title5=Traffic Limit Reached!
N_Desc5=Your PC have reached the limit of your network traffic!

;	System Control

SC_Title=System Control
SC_Shutdown_TTTitle=Shutdown
SC_Shutdown_TTText=Turns off computer
SC_Restart_TTTitle=Restart
SC_Restart_TTText=Restarts computer
SC_Lock_TTTitle=Lock
SC_Lock_TTText=Locks computer
SC_Sleep_TTTitle=Sleep
SC_Sleep_TTText=Sets computer into sleep
SC_Logout_TTTitle=Logout
SC_Logout_TTText=Logs out of user

;	Clipboard

CB_Title=Clipboard
CB_Line=Selected clip is highlighted at the top
CB_Line2=Double-click this title to clear all clips
CB_Line3=Note
CB_Line4=Multi-line clips only display the first line