;	Notifications > Net Total

;------------
;	Meters
;------------

[Content-Title]
Meter=String
MeterStyle=TEXT
FontSize=13
Text=#N_Title5#
ClipString=2
ClipStringW=270
X=-30r
Y=30r

[Content-Seperator]
Meter=Image
SolidColor=255,255,255,30
W=200
H=1
X=0r
Y=25r

[Content-Description]
Meter=String
MeterStyle=TEXT
FontSize=9
Text=#N_Desc5#
ClipString=2
ClipStringW=220
X=0r
Y=10r

[Content-Icon]
Meter=Image
ImageName=#@#\Images\Icons\update.png
X=220r
Y=-25r
W=55
H=55