;------------
;	Meters
;------------

;	Disk #1

[Disk-1-Label]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=28r
W=190
H=14
Text=#disk1#\

[Disk-1-Value]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-1
MeasureName2=Measure-Total-Disk-1
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk1#\"]

[Disk-1-Bar]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-1
X=10
Y=16r
W=190
H=1

;	Disk #2

[Disk-2-Label]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D2Y#
W=190
H=14
Text=#disk2#\
Hidden=#D2A#

[Disk-2-Value]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-2
MeasureName2=Measure-Total-Disk-2
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk2#\"]
Hidden=#D2A#

[Disk-2-Bar]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-2
X=10
Y=#D2Y2#
W=190
H=1
Hidden=#D2A#

;	Disk #3

[Disk-3-Label]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D3Y#
W=190
H=14
Text=#disk3#\
Hidden=#D3A#

[Disk-3-Value]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-3
MeasureName2=Measure-Total-Disk-3
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk3#\"]
Hidden=#D3A#

[Disk-3-Bar]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-3
X=10
Y=#D3Y2#
W=190
H=1
Hidden=#D3A#

;	Disk #4

[Disk-4-Label]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D4Y#
W=190
H=14
Text=#disk4#\
Hidden=#D4A#

[Disk-4-Value]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-4
MeasureName2=Measure-Total-Disk-4
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk4#\"]
Hidden=#D4A#

[Disk-4-Bar]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-4
X=10
Y=#D4Y2#
W=190
H=1
Hidden=#D4A#

;	Disk #5

[Disk-5-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D5Y#
W=190
H=14
Text=#disk5#\
Hidden=#D5A#

[Disk-5-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-5
MeasureName2=Measure-Total-Disk-5
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk5#\"]
Hidden=#D5A#

[Disk-5-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-5
X=10
Y=#D5Y2#
W=190
H=1
Hidden=#D5A#

;	Disk #6

[Disk-6-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D6Y#
W=190
H=14
Text=#disk6#\
Hidden=#D6A#

[Disk-6-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-6
MeasureName2=Measure-Total-Disk-6
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk6#\"]
Hidden=#D6A#

[Disk-6-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-6
X=10
Y=#D6Y2#
W=190
H=1
Hidden=#D6A#




;	Disk #7

[Disk-7-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D7Y#
W=190
H=14
Text=#disk7#\
Hidden=#D7A#

[Disk-7-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-7
MeasureName2=Measure-Total-Disk-7
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk7#\"]
Hidden=#D7A#

[Disk-7-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-7
X=10
Y=#D7Y2#
W=190
H=1
Hidden=#D7A#

;	Disk #8

[Disk-8-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D8Y#
W=190
H=14
Text=#disk8#\
Hidden=#D8A#

[Disk-8-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-8
MeasureName2=Measure-Total-Disk-8
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk8#\"]
Hidden=#D8A#

[Disk-8-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-8
X=10
Y=#D8Y2#
W=190
H=1
Hidden=#D8A#

;	Disk #9

[Disk-9-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D9Y#
W=190
H=14
Text=#disk9#\
Hidden=#D9A#

[Disk-9-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-9
MeasureName2=Measure-Total-Disk-9
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk9#\"]
Hidden=#D9A#

[Disk-9-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-9
X=10
Y=#D9Y2#
W=190
H=1
Hidden=#D9A#

;	Disk #10

[Disk-10-Label-Meter]
Meter=String
MeterStyle=LEFT-ALIGN
X=10
Y=#D10Y#
W=190
H=14
Text=#disk10#\
Hidden=#D10A#

[Disk-10-Value-Meter]
Meter=String
MeterStyle=RIGHT-ALIGN
MeasureName=Measure-Used-Disk-10
MeasureName2=Measure-Total-Disk-10
X=200
Y=0r
W=190
H=14
Text=%1B / %2B #SS_S_D_Used#
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#Disk10#\"]
Hidden=#D10A#

[Disk-10-Bar-Meter]
Meter=Bar
MeterStyle=BAR
MeasureName=Measure-Used-Disk-10
X=10
Y=#D10Y2#
W=190
H=1
Hidden=#D10A#