;	Font Changer > Fonts List #2

[Font-1]
Meter=String
MeterStyle=BUTTONS
Text=RobotoMono
X=([Font-Seperator:X]+0)
Y=([Font-Seperator:Y]+10)
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "RobotoMono" "#@#\Addons\variables.inc"]#Refreshes#

[Font-2]
Meter=String
MeterStyle=BUTTONS
Text=Ubuntu
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Ubuntu" "#@#\Addons\variables.inc"]#Refreshes#

[Font-3]
Meter=String
MeterStyle=BUTTONS
Text=FONT
X=0r
Y=25r
Hidden=1
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "FONT" "#@#\Addons\variables.inc"]#Refreshes#

[Font-4]
Meter=String
MeterStyle=BUTTONS
Text=FONT
X=0r
Y=25r
Hidden=1
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "FONT" "#@#\Addons\variables.inc"]#Refreshes#

[Font-5]
Meter=String
MeterStyle=BUTTONS
Text=FONT
X=0r
Y=25r
Hidden=1
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "FONT" "#@#\Addons\variables.inc"]#Refreshes#

[Font-6]
Meter=String
MeterStyle=BUTTONS
Text=FONT
X=0r
Y=25r
Hidden=1
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "FONT" "#@#\Addons\variables.inc"]#Refreshes#

[Font-7]
Meter=String
MeterStyle=BUTTONS
Text=FONT
X=0r
Y=25r
Hidden=1
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "FONT" "#@#\Addons\variables.inc"]#Refreshes#

;	Max amount of fonts on one page