;	Font Changer > Fonts List #1

[Font-1]
Meter=String
MeterStyle=BUTTONS
Text=Trebuchet MS
X=([Font-Seperator:X]+0)
Y=([Font-Seperator:Y]+10)
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Trebuchet MS" "#@#\Addons\variables.inc"]#Refreshes#

[Font-2]
Meter=String
MeterStyle=BUTTONS
Text=Bahnschrift
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Bahnschrift" "#@#\Addons\variables.inc"]#Refreshes#

[Font-3]
Meter=String
MeterStyle=BUTTONS
Text=Product Sans
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Product Sans" "#@#\Addons\variables.inc"]#Refreshes#

[Font-4]
Meter=String
MeterStyle=BUTTONS
Text=Gotham Book
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Gotham Book" "#@#\Addons\variables.inc"]#Refreshes#

[Font-5]
Meter=String
MeterStyle=BUTTONS
Text=Oswald
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Oswald" "#@#\Addons\variables.inc"]#Refreshes#

[Font-6]
Meter=String
MeterStyle=BUTTONS
Text=PlayfairDisplay
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "PlayfairDisplay" "#@#\Addons\variables.inc"]#Refreshes#

[Font-7]
Meter=String
MeterStyle=BUTTONS
Text=Poppins
X=0r
Y=25r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\Click.wav"][!WriteKeyValue Variables #Font-To-Change# "Poppins" "#@#\Addons\variables.inc"]#Refreshes#

;	Max amount of fonts on one page