;	This file containts language of the panel. 
;	ENGLISH (BASIC)

[Variables]

;-----------
;	Main
;-----------

Main_Thanks=Thank you for downloading my suite
Main_Configure=Configure Suite

;-----------
;	Popups
;-----------

;	Uninstall

Panel_Content_Uninstall_Title=Uninstall Warning
Panel_Content_Uninstall_Question=Do you want to remove this bundle?
Panel_Content_Uninstall_Button=Uninstall

;-----------
;	Panel
;-----------

Panel_SideBar_Menu=Menu
Panel_SideBar_HomePage=Home Page
Panel_SideBar_Settings=Settings
Panel_SideBar_Update=Update
Panel_SideBar_Appearance=Appearance
Panel_SideBar_Skins=Skins
Panel_SideBar_Information=About
Panel_SideBar_Wiki=Wiki
Panel_SideBar_Credits=Credits
Panel_SideBar_Change_Log=Change Log

;	Home Page

Panel_HomePage_Content=Ashuramaru Bundle is a skin bundle coded and designed for any beginner with rainmeter who doesnt know how to make skins. It allows for maxiumum customization like backgrounds, colors, icons etc. This bundle contains skins made by diferent authors with a little bit of mine edited code in them.

;	Settings

Panel_Content_Settings=Every skin which comes with this bundle has implemented some sort of a customization too it for you to play with.
Panel_Content_Settings_1=Panel Settings
Panel_Content_Settings_2=Skins Settings
Panel_Content_Settings_3=Uninstall
Panel_Content_Info_Title=Available Actions
Panel_Content_Info=LMB > To set value of parameter#CRLF#RMB > To set default value of parameter
Panel_Content_Yes=Yes
Panel_Content_No=No
Panel_Content_Cancel=Cancel
SK_ON=ON
SK_OFF=OFF

;	Settings \ Panel Settings

Panel_Content_Settings_Panel_Language=Language
Panel_Content_Settings_Panel_Quality=Panel Quality
Panel_Content_Settings_Panel_Quality_Low=Low
Panel_Content_Settings_Panel_Quality_Medium=Medium
Panel_Content_Settings_Panel_Quality_High=High
Panel_Content_Settings_Panel_Notyfications=Notyfications
Panel_Content_Settings_Panel_Tray_Icon=Tray Icon

;	Settings \ Skins Settings

Panel_Content_Settings_Skins_1=Statistics Settings
Panel_Content_Settings_Skins_2=Processes Settings
Panel_Content_Settings_Skins_3=Elegant Clock Settings
Panel_Content_Settings_Skins_4=Dock Settings
Panel_Content_Settings_Skins_5=Translucent Taskbar Settings
Panel_Content_Settings_Skins_6=CyberSearch Settings
Panel_Content_Settings_Skins_7=TaskbarX Settings
Panel_Content_Settings_Skins_8=VectorCopy Settings

;	Settings \ Skins Settings \ Statistics

Panel_Content_Settings_Skins_Statistics_Content=Statistics Combined Type
Panel_Content_Settings_Skins_Statistics_Combined_Type=Type
Panel_Content_Settings_Skins_Statistics_Disks_Content=Statistics Disks
Panel_Content_Settings_Skins_Statistics_Disk=Disk
Panel_Content_Settings_Skins_Statistics_Combined_Disk_Type=Statistics Combined Disks Type
Panel_Content_Settings_Skins_Statistics_Combined_Disk_Type_Classic=Classic
Panel_Content_Settings_Skins_Statistics_Combined_Disk_Type_Extended=Extended
Panel_Content_Settings_Skins_Statistics_Measures_Engine=Statistics Measures Engine
Panel_Content_Settings_Skins_Statistics_Net_Total_Limiter=Statistics Net Total Limiter
Panel_Content_Settings_Skins_Statistics_Detailed_Graphs=Statistics Detailed Graphs
Panel_Content_Settings_Skins_Statistics_Disks_Letters=Statistics Disks Letters
Panel_Content_Settings_Skins_Statistics_Net_Total_Limit=Statistics Net Total Limit
Panel_Content_Settings_Skins_Statistics_GPU_Vram_Memory=Statistics GPU VRAM Memory
Panel_Content_Settings_Skins_Statistics_Ping_Host=Statistics Ping Host
Panel_Content_Settings_Skins_Statistics_Network_Segment=Statistics Network Segment
Panel_Content_Settings_Skins_Statistics_Network_Segment_Latency=Latency
Panel_Content_Settings_Skins_Statistics_Network_Segment_Upload=Upload
Panel_Content_Settings_Skins_Statistics_Network_Segment_Download=Download
Panel_Content_Settings_Skins_Statistics_Network_Segment_Speed=Speed
Panel_Content_Settings_Skins_Statistics_Network_Segment_Traffic=Traffic
Panel_Content_Settings_Skins_Statistics_System_CPU_Segment=Statistics System CPU Segment
Panel_Content_Settings_Skins_Statistics_System_CPU_Segment_Usage=Usage
Panel_Content_Settings_Skins_Statistics_System_CPU_Segment_Clock=Clock
Panel_Content_Settings_Skins_Statistics_System_CPU_Segment_Temp=Temp
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment=Statistics System GPU Segment
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Usage=Usage
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Clock=Clock
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Temp=Temp
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Memory_Clock=Memory Clock
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Memory_Usage=Memory Usage
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Memory_Usage_%=Memory Usage %
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Fan_Speed=Fan Speed
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Fan_Speed_RPM=Fan Speed RPM
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Voltage=Voltage
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Ram_%=Ram %
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Ram=Ram
Panel_Content_Settings_Skins_Statistics_System_GPU_Segment_Swap=Swap
Panel_Content_Settings_Skins_Statistics_System_Segment_Framerate=Framerate
Panel_Content_Settings_Skins_Statistics_Logging=Statistics Logging
Panel_Content_Settings_Skins_Statistics_Logging_Delay=Statistics Logging Delay

;	Settings \ Skins Settings \ Processes

Panel_Content_Settings_Skins_Processes_Content=Processes Graphs

;	Settings \ Skins Settings \ Elegant Clock

Panel_Content_Settings_Skins_Elegant_Clock_Time_Type=Elegant Clock Time Type
Panel_Content_Settings_Skins_Elegant_Clock_Day_Info=Elegant Clock Day Info
Panel_Content_Settings_Skins_Elegant_Clock_Year_Info=Elegant Clock Year Info

;	Settings \ Skins Settings \ Dock

Panel_Content_Settings_Skins_Dock_Lenght=Dock Lenght
Panel_Content_Settings_Skins_Dock_Icons=Icons
Panel_Content_Settings_Skins_Dock_Program=Dock Program
Panel_Content_Settings_Skins_Dock_Icon_Name=Icon Name
Panel_Content_Settings_Skins_Dock_Default_Path=Input program path here
Panel_Content_Settings_Skins_Dock_Path_Fix_Title=Repair path
Panel_Content_Settings_Skins_Dock_Path_Fix=LMB > To set default value of parameter
Panel_Content_Settings_Skins_Dock_Icons_Folder=Icons Folder

;	Settings \ Skins Settings \ Translucent Taskbar

Panel_Content_Settings_Skins_Translucent_Taskbar_Type=Translucent Taskbar Type
Panel_Content_Settings_Skins_Translucent_Taskbar_Type_Transparent=Transparent
Panel_Content_Settings_Skins_Translucent_Taskbar_Type_Blured=Blured

;	Settings \ Skins Settings \ CyberSearch

Panel_Content_Settings_Skins_CyberSearch_Engine=CyberSearch Engine

;	Settings \ Skins Settings \ TaskbarX

Panel_Content_Settings_Skins_TaskbarX_Type=TaskbarX Type
Panel_Content_Settings_Skins_TaskbarX_Type_Transparent=Transparent
Panel_Content_Settings_Skins_TaskbarX_Type_Blured=Blured
Panel_Content_Settings_Skins_TaskbarX_Type_Acrylic=Acrylic
Panel_Content_Settings_Skins_TaskbarX_Type_Gradient=Gradient
Panel_Content_Settings_Skins_TaskbarX_Type_Solid=Solid
Panel_Content_Settings_Skins_TaskbarX_Centered=TaskbarX Centered
Panel_Content_Settings_Skins_TaskbarX_Tray_Icon=TaskbarX Tray Icon
Panel_Content_Settings_Skins_TaskbarX_Segments=TaskbarX Segments
Panel_Content_Settings_Skins_TaskbarX_Pause=TaskbarX Pause
Panel_Content_Settings_Skins_TaskbarX_Gradient=TaskbarX Gradient
Panel_Content_Settings_Skins_TaskbarX_Animation=TaskbarX Animation
Panel_Content_Settings_Skins_TaskbarX_Animation_List=List of all available animations

;	Settings \ Skins Settings \ VectorCopy

Panel_Content_Settings_Skins_VectorCopy_Type=Visualizer Type
Panel_Content_Settings_Skins_VectorCopy_Type_Bars=Bars
Panel_Content_Settings_Skins_VectorCopy_Type_Vector=Vector
Panel_Content_Settings_Skins_VectorCopy_Color_Type=Visualizer Color Type
Panel_Content_Settings_Skins_VectorCopy_Color_Type_Color=Color
Panel_Content_Settings_Skins_VectorCopy_Color_Type_Wallpaper=Wallpaper
Panel_Content_Settings_Skins_VectorCopy_Inverted=Visualizer Inverted
Panel_Content_Settings_Skins_VectorCopy_Scale=Visualizer Scale
Panel_Content_Settings_Skins_VectorCopy_Scale_Small=Small
Panel_Content_Settings_Skins_VectorCopy_Scale_Normal=Normal
Panel_Content_Settings_Skins_VectorCopy_Scale_Big=Big
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type=Visualizer Wallpaper Type
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type_Foreground=Foreground
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type_Background=Background
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type_Light=Light
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type_Dark=Dark
Panel_Content_Settings_Skins_VectorCopy_Wallpaper_Type_Average=Average
Panel_Content_Settings_Skins_VectorCopy_Alpha=Visualizer Alpha
Panel_Content_Settings_Skins_VectorCopy_Bar_Width=Visualizer Bar Width
Panel_Content_Settings_Skins_VectorCopy_Bar_Spacing=Visualizer Bar Spacing
Panel_Content_Settings_Skins_VectorCopy_Bar_Roundess=Visualizer Bar Roundness
Panel_Content_Settings_Skins_VectorCopy_Height=Visualizer Height
Panel_Content_Settings_Skins_VectorCopy_Vector_Width=Visualizer Vector Width
Panel_Content_Settings_Skins_VectorCopy_Rotation=Visualizer Rotation

;	Update

Panel_Update_Content=Whenever the new release of the bundle will come out you will get notification or you can check it right here.
Panel_Upadate_Download=Download
Panel_Update_Checking_For_Updates=Checking for updates...
Panel_Update_Up_To_Date=No updates found
Panel_Update_Development_Version=Development version
Panel_Update_New=is available to download!

;	Appearance

Panel_Appearance_Content=You can customize all skins included in the bundle here, have fun with adjusting the bundle to your needs.
Panel_Appearance_Adjust_Colors=Adjust Colors
Panel_Appearance_Adjust_Fonts=Adjust Fonts
Panel_Appearance_Adjust_Background=Adjust Background

;	Appearance \ Colors

Panel_Appearance_Adjust_Colors_Title=Which skin colors you want to customize?
Panel_Content_Appearance_Color_Info=LMB > To to open ColorPicker#CRLF#RMB > To set default color
Panel_Appearance_Adjust_Colors_IllustroColors=Illustro Colors
Panel_Appearance_Adjust_Colors_VectorCopyColors=VectorCopy Colors
ColorDescription=Hover on color to see description

;	Appearance \ Colors \ Illustro

IllustroPrimaryColorDescription=Titles and headers
IllustroSecondaryColorDescription=Label names
IllustroTertiaryColorDescription=Values
IllustroQuaternaryColorDescription=Bars
IllustroQuinaryColorDescription=Time, date and year values
IllustroSenaryColorDescription=Graphs
IllustroSeptenaryColorDescription=Seperators

;	Appearance \ Colors \ VectorCopy

VectorCopyPrimaryColorDescription=Visualizer Bars

;	Appearance \ Fonts

Panel_Appearance_Adjust_Fonts_Title=Chose illustro font
Panel_Appearance_Adjust_Fonts_Info=List of default installed fonts
Panel_Appearance_Adjust_Fonts_Info2=All windows fonts and every font in Fonts folder

;	Appearance \ Background

Panel_Appearance_Adjust_Background_Title=Chose illustro background

;	Skins

Panel_Skins_Content=Chose type of skin you want to operate with.
Panel_Skins_Type1=Kurou Skins
Panel_Skins_Type2=Other Skins

;	About

Panel_About_Content=All information about the panel and release are stored here.
Panel_About_Version=Version
Panel_About_Build=Build
Panel_About_Released=Released
Panel_About_License=License
Panel_About_Copyright=Copyright
Panel_About_Plugins=Plugins
Panel_About_Plugins_Title=List of all plugins used in the bundle
Panel_About_Skins=Skins
Panel_About_Skins_Title=List of all skins used in the bundle

;	Notifications

N_Title=New update available!
N_Desc=Check Update tab in panel for more info!
N_Title3=An Error Accured
N_Desc3=Error Code
N_Title4=Notifications enabled!
N_Desc4=Now Notifications will show every time certain events happen!
N_Title5=Traffic Limit Reached!
N_Desc5=Your PC have reached the limit of your network traffic!

;-----------
;	Supported Skins
;-----------

;	Clock

SS_C_Day=Day
SS_C_Week=Week
SS_C_Quarter=Quarter

;	Battery

SS_B_Title=Battery
SS_B_Level=Battery Level
SS_B_Left=Left

;	Recycle Bin

SS_RB_Title=Recycle Bin
SS_RB_Items=Items
SS_RB_ToolTipText=Click to empty bin
SS_RB_ToolTipText2=Click to open bin

;	Statistics

SS_S_N_Title=Network
SS_S_N_Latency=Latency
SS_S_N_Upload=Upload
SS_S_N_Download=Download
SS_S_N_Speed=Speed
SS_S_N_Traffic=Traffic
SS_S_S_Title=System
SS_S_S_CPU_U=CPU Usage
SS_S_S_CPU_T=CPU Temperature
SS_S_S_CPU_C=CPU Clock
SS_S_S_GPU_U=GPU Usage
SS_S_S_GPU_T=GPU Temperature
SS_S_S_GPU_C=GPU Core Clock
SS_S_S_GPU_M=GPU Memory Clock
SS_S_S_GPU_M2=GPU Memory Usage
SS_S_S_GPU_V=GPU Voltage
SS_S_S_GPU_FS=GPU Fan Speed
SS_S_S_RAM=RAM Usage
SS_S_S_SWAP=SWAP Usage
SS_S_D_Title=Disks
SS_S_D_Used=used

;	Statistics Detailed

SD_D_Title=Drives
SS_D_Drive=Drive
SD_D_Used=Used
SD_D_Total=Total
SD_D_Read=Read
SD_D_Write=Write
SD_D_Activity=Activity
SD_G_Title=Graphics
SD_G_Core_Clock=Core Clock
SD_G_Memory_Clock=Memory Clock
SD_G_Power=Power
SD_G_Temperature=Temperature
SD_G_Load=Load
SD_G_Fan_Speed=Fan Speed
SD_G_Memory=Memory
SD_M_Title=Memory
SD_M_Used=Used
SD_M_Free=Free
SD_N_Title=Network
SD_N_External=External
SD_N_Internal=Internal
SD_N_Total=Total
SD_N_Latency=Latency
SD_N_Upload=Upload
SD_N_Download=Download
SD_P_Title=Processor
SD_P_Core_Clock=Core Clock
SD_P_Temperature=Temperature
SD_P_Handle_Count=Handle Count
SD_P_Thread_Count=Thread Count
SD_P_Uptime=Uptime
SD_P_Total_Usage=Total Usage

;	Processes

SS_PR_Title=Top CPU Processes
SS_PR_Title2=Top GPU Processes
SS_PR_Title3=Top IO Processes
SS_PR_Title4=Top RAM Processes
SS_PR_ToolTipTextTitle=Top Processes
SS_PR_ToolTipText=Use SCRLUP and SCRLDOWN to change config

;	Hardware Info

SS_HI_Title=Hardware Info
SS_HI_Motherboard=Motherboard
SS_HI_Sound_Devices=Sound Devices
SS_HI_Network_Adapters=Network Adapters

;	Dock

SS_D_ToolTipTextTitle=Icon Shortcut
SS_D_ToolTipText=LMB > Open | SRC > Reset

;	Volume Control

V_C_Title=Volume Control
V_OM=Open Mixer
V_ND=Next Device
V_PD=Previous Device
V_D=Volume Down
V_U=Volume Up
V_TM=Toggle Mute

;	System Control

SC_Title=System Control
SC_Shutdown_TTTitle=Shutdown
SC_Shutdown_TTText=Turns off computer
SC_Restart_TTTitle=Restart
SC_Restart_TTText=Restarts computer
SC_Lock_TTTitle=Lock
SC_Lock_TTText=Locks computer
SC_Sleep_TTTitle=Sleep
SC_Sleep_TTText=Sets computer into sleep
SC_Logout_TTTitle=Logout
SC_Logout_TTText=Logs out of user

;	Clipboard

CB_Title=Clipboard
CB_Line=Selected clip is highlighted at the top
CB_Line2=Double-click this title to clear all clips
CB_Line3=Note
CB_Line4=Multi-line clips only display the first line