;	Ashuramaru Bundle Settings\Skins\Dock 2nd Page

;	This is additional file for panel

;	Last edit date: 21.06.2022

;------------
;	Measures
;------------

;	Dock Program 1

[Settings-Dock-Program-1-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-1:X]+0)
Y=([Settings-Dock-Program-Path-1:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-1 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program 2

[Settings-Dock-Program-2-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-2:X]+0)
Y=([Settings-Dock-Program-Path-2:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-2 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program 3

[Settings-Dock-Program-3-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-3:X]+0)
Y=([Settings-Dock-Program-Path-3:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-3 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program 4

[Settings-Dock-Program-4-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-4:X]+0)
Y=([Settings-Dock-Program-Path-4:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-4 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program 5

[Settings-Dock-Program-5-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-5:X]+0)
Y=([Settings-Dock-Program-Path-5:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-5 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program 6

[Settings-Dock-Program-6-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Path-6:X]+0)
Y=([Settings-Dock-Program-Path-6:Y]+0)
W=600
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=Input program path here
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Exe-6 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 1

[Settings-Dock-Program-Icon-1-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-1:X]+0)
Y=([Settings-Dock-Program-Icon-1:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-1 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 2

[Settings-Dock-Program-Icon-2-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-2:X]+0)
Y=([Settings-Dock-Program-Icon-2:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-2 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 3

[Settings-Dock-Program-Icon-3-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-3:X]+0)
Y=([Settings-Dock-Program-Icon-3:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-3 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 4

[Settings-Dock-Program-Icon-4-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-4:X]+0)
Y=([Settings-Dock-Program-Icon-4:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-4 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 5

[Settings-Dock-Program-Icon-5-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-5:X]+0)
Y=([Settings-Dock-Program-Icon-5:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-5 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icon 6

[Settings-Dock-Program-Icon-6-Measure]
Measure=Plugin
Plugin=InputText
X=([Settings-Dock-Program-Icon-6:X]+0)
Y=([Settings-Dock-Program-Icon-6:Y]+0)
W=142
H=34
FontSize=20
FontColor=255,255,255,255
SolidColor=70,70,70,255
AntiAlias=1
DefaultValue=new
FocusDismiss=0
Command1=[!WriteKeyValue Variables Dock-Icon-6 "$UserInput$" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;------------
;	Meters
;------------

;	Dock Program #1

[Settings-Dock-Program-1]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 1
X=70
Y=60

[Settings-Dock-Program-Icon-1]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-1-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-1  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Info]
Meter=Image
ImageName=#@#\Images\Icons\info.png
W=30
H=30
X=([Settings-Dock-Program-1:X]+250)
Y=([Settings-Dock-Program-1:Y]+0)
ToolTipTitle=#Panel_Content_Info_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Info#

[Settings-Dock-Program-Path-1]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-1#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-1-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-1 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]
Hidden=0

;	Dock Program #2

[Settings-Dock-Program-2]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 2
X=70
Y=50r

[Settings-Dock-Program-Icon-2]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-2-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-2  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-2]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-2#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-2-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-2 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program #3

[Settings-Dock-Program-3]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 3
X=70
Y=50r

[Settings-Dock-Program-Icon-3]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-3-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-3  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-3]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-3#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-3-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-3 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program #4

[Settings-Dock-Program-4]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 4
X=70
Y=50r

[Settings-Dock-Program-Icon-4]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-4-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-4  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-4]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-4#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-4-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-4 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program #5

[Settings-Dock-Program-5]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 5
X=70
Y=50r

[Settings-Dock-Program-Icon-5]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-5-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-5  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-5]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-5#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-5-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-5 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Program #6

[Settings-Dock-Program-6]
Meter=String
MeterStyle=H2
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Program# 6
X=70
Y=50r

[Settings-Dock-Program-Icon-6]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icon_Name#
W=140
X=458r
Y=0r
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-Icon-6-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Icon-6  "new" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-6]
Meter=String
MeterStyle=BUTTONS
FontSize=20
Text=#Dock-Exe-6#
X=70
Y=40r
W=600
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!CommandMeasure Settings-Dock-Program-6-Measure "ExecuteBatch 1"]
RightMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-6 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Path Repairs

[Settings-Dock-Program-Path-Repair-1]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-1:X]+570)
Y=([Settings-Dock-Program-Path-1:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-1 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-Repair-2]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-2:X]+570)
Y=([Settings-Dock-Program-Path-2:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-2 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-Repair-3]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-3:X]+570)
Y=([Settings-Dock-Program-Path-3:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-3 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-Repair-4]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-4:X]+570)
Y=([Settings-Dock-Program-Path-4:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-4 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-Repair-5]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-5:X]+570)
Y=([Settings-Dock-Program-Path-5:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-5 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

[Settings-Dock-Program-Path-Repair-6]
Meter=Image
ImageName=#@#\Images\Icons\fix.png
ImageTint=100,100,100,50
W=25
H=25
X=([Settings-Dock-Program-Path-6:X]+570)
Y=([Settings-Dock-Program-Path-6:Y]+5)
ToolTipTitle=#Panel_Content_Settings_Skins_Dock_Path_Fix_Title#
ToolTipIcon=#@#\Images\Icons\Ashuramaru-Bundle.ico
ToolTipType=2
ToolTipText=#Panel_Content_Settings_Skins_Dock_Path_Fix#
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables Dock-Exe-6 "#Panel_Content_Settings_Skins_Dock_Default_Path#" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#][!RefreshGroup "Ashuramaru-Bundle Dock"]

;	Dock Icons Folder

[Settings-Dock-Icon-Folder]
Meter=String
MeterStyle=TEXT
FontSize=20
Text=#Panel_Content_Settings_Skins_Dock_Icons_Folder#
X=720
Y=220
W=165
Angle=(Rad(90))

[Settings-Dock-Icon-Folder-Area]
Meter=Image
SolidColor=150,150,150,20
X=-33r
Y=-5r
W=35
H=165
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][#ROOTCONFIGPATH#\@Resources\Images\Icons\Dock]

;	Previous Page Area

[Settings-Dock-Previous-Page-Area]
Meter=Image
SolidColor=100,100,100,10
W=50
H=542
X=742
Y=49
MouseOverAction=[!SetOption #CURRENTSECTION# SolidColor 100,100,100,40][!SetOption Settings-Dock-Previous-Page-Icon ImageTint 200,200,200,60][!UpdateMeter #CURRENTSECTION#][!UpdateMeter Settings-Dock-Previous-Page-Icon]
MouseLeaveAction=[!SetOption #CURRENTSECTION# SolidColor 100,100,100,10][!SetOption Settings-Dock-Previous-Page-Icon ImageTint 200,200,200,30][!UpdateMeter #CURRENTSECTION#][!UpdateMeter Settings-Dock-Previous-Page-Icon]
LeftMouseDownAction=[Play "#@#\Sounds\Buttons\click.wav"][!WriteKeyValue Variables CurrentPage "Settings\Skins\Dock\page1" "#@#\Addons\variables.inc"][!Refresh #CURRENTCONFIG#]

[Settings-Dock-Previous-Page-Icon]
Meter=Image
ImageName=#@#\Images\Icons\left-arrow.png
ImageTint=200,200,200,30
W=30
H=30
X=10r
Y=230r