[Variables]

;------------
;	Global
;------------

MainLanguage=EN
IllustroFont=Bahnschrift
NotificationsContent=error
ErrorCode=100

;	Information about the bundle

Version=1.1.0
Build=1207221507
LicenseType=CC BY-NC-SA 4.0
Released=-

;	Multiple bangs combined into one variable

Refreshes=[!RefreshGroup "Ashuramaru-Bundle Group"][!RefreshGroup "Ashuramaru-Bundle Statistics"][!RefreshGroup "Ashuramaru-Bundle Clock"][!RefreshGroup "Ashuramaru-Bundle Top-Processes"][!RefreshGroup "Ashuramaru-Bundle CyberSearch"][!RefreshGroup "Ashuramaru-Bundle Dock"][!RefreshGroup "Ashuramaru-Bundle Dock-Single"][!RefreshGroup "Ashuramaru-Bundle-Visualizers-Group"][!RefreshGroup "Ashuramaru-Bundle Setup"][!RefreshGroup "Ashuramaru-Bundle Statistics-Detailed"][!RefreshGroup "ColorPicker"]

Deactivates=[!DeactivateConfigGroup "Ashuramaru-Bundle Group"][!DeactivateConfigGroup "Ashuramaru-Bundle Statistics"][!DeactivateConfigGroup "Ashuramaru-Bundle Clock"][!DeactivateConfigGroup "Ashuramaru-Bundle Top-Processes"][!DeactivateConfigGroup "Ashuramaru-Bundle CyberSearch"][!DeactivateConfigGroup "Ashuramaru-Bundle Dock"][!DeactivateConfigGroup "Ashuramaru-Bundle Dock-Single"][!DeactivateConfigGroup "Ashuramaru-Bundle-Visualizers-Group"][!DeactivateConfigGroup "Ashuramaru-Bundle Setup"][!DeactivateConfigGroup "Ashuramaru-Bundle Statistics-Detailed"]

;	Frost Glass Plugin

OpaqueBG=None

;------------
;	Panel
;------------

CurrentPage=home
PageColor=200,200,200
PageColor1=255,0,0
PageColor2=200,200,200
PageColor3=200,200,200
PageColor4=200,200,200
PageColor5=200,200,200
PageColor6=200,200,200
SidebarInfoState=1

State-Statistics-Combined=1
State-Statistics-Minimal=1
State-Statistics-Individual=1
State-Statistics-Detailed=1
State-Processes-Combined=1
State-Processes-Individual=1
State-Elegant-Clock=1
State-Translucent-Taskbar=1
State-TaskbarX=1
State-VectorCopy=1
State-Battery=1
State-Recycle-Bin=1
State-Hardware-Info=1
State-Dock=1
State-CyberSearch=1
State-Notes=1
State-Volume-Control=1
State-System-Control=1
State-Clipboard=1

PopUpsUninstall=1

;	Appearance

BackgroundImageToChange=Solid
Background-Image=#@#\Images\Backgrounds\#BackgroundImageToChange#.png
Background-Image-Blank=#@#\Images\Backgrounds\#BackgroundImageToChange#-Blank.png
Background-Image-Header=#@#\Images\Backgrounds\#BackgroundImageToChange#-Header.png
Background-Image-Header-Top=#@#\Images\Backgrounds\#BackgroundImageToChange#-Header-Top.png
Panel-Background=#@#\Images\Backgrounds\Panel-Background.png
Notyfications-Background=#@#\Images\Backgrounds\Panel-Background.png

PBSA=0
PBSB=0

BTOUA=0
BTO=1
BTOUA2=0
BTO2=1
BTOUA3=0
BTO3=1
BTOUA4=0
BTO4=1
BTOUA5=0
BTO5=1
BTOUA6=0
BTO6=1
BTOUA7=0
BTO7=1
BTOUA8=0
BTO8=1
BTOUA9=1
BTO9=0

ASIUA=0
ASI=1
ASIUA2=0
ASI2=1
ASIUA3=0
ASI3=1
ASIUA4=1
ASI4=0

;	ColorPicker

Color-To-Paint=ISenaryColor

;	Illustro Colors

IPrimaryColor=255,255,255
ISecondaryColor=255,255,255
ITertiaryColor=255,255,255
IQuaternaryColor=255,0,0
IQuinaryColor=255,0,0
ISenaryColor=255,0,0
ISeptenaryColor=255,255,255

;	VectorCopy Colors

VCPrimaryColor=255,0,0

;------------
;	Panel - Settings
;------------

;	Panel

TOUA=0
TO=1

GMO=1
GMOFF=0
NFOFF=0
NFMO=1
LOFF=0
LON=1

GMO1UA=0
GMO1=1
GMO2UA=0
GMO2=1
GMO3UA=0
GMO3=1
GMO4UA=0
GMO4=1
GMO5UA=0
GMO5=1
GMO6UA=0
GMO6=1
GMO7UA=0
GMO7=1
GMO8UA=0
GMO8=1

QOUA=0
QOA=1
QOUA2=0
QOA2=1
QOUA3=1
QOA3=0

;	Statistics

LO=0
LOUA=1
LO2=1
LOUA2=0

TTVO=1
TTVOUA=0
TTVO2=0
TTVOUA2=1

VVO=1
VVOUA=0
VVO2=1
VVOUA2=0
VVO3=1
VVOUA3=0
VVO4=1
VVOUA4=0

SCTOO=0
SCTOY22=28
SCTOO3=0
SCTOY=3r
SCTOYY=10r
SCTOO2=0
SCTOY2=3r
SCTOYY2=10r

SMEUA=1
SMEA=0
SMEUA2=0
SMEA2=1

SDTUA=1
SDTA=0
SDTUA2=0
SDTA2=1

;	Processes

PVO=1
PVOUA=0
PVO2=1
PVOUA2=0

PGOUA=1
PGOA=0

;	Variations

PSSCTUA=0
PSSCTA=1
PSSCTUA2=0
PSSCTA2=1
PSSCTUA3=1
PSSCTA3=0
PSSCTUA4=0
PSSCTA4=1
PSSCTUA5=0
PSSCTA5=1
PSSCTUA6=0
PSSCTA6=1
PSSCTUA7=0
PSSCTA7=1

SGA=1
SGA2=1
SGA3=1
SGA4=1
SGA5=1
SGUA=0
SGUA2=0
SGUA3=0
SGUA4=0
SGUA5=0

SLNLUA=1
SLNLA=0
SLNUUA=1
SLNUA=0
SLNDUA=1
SLNDA=0
SLNTUA=1
SLNTA=0
SLNSUA=1
SLNSA=0

SLSCUUA=1
SLSCUA=0
SLSCCUA=1
SLSCCA=0
SLSCTUA=1
SLSCTA=0
SLSGUUA=1
SLSGUA=0
SLSGCUA=1
SLSGCA=0
SLSGMCUA=1
SLSGMCA=0
SLSGMCUA2=1
SLSGMCA2=0
SLSGMCUA3=1
SLSGMCA3=0
SLSGVUA=1
SLSGVA=0
SLSGTUA=1
SLSGTA=0
SLSGFSUA=1
SLSGFSA2=0
SLSGFSUA2=1
SLSGFSA=0
SLSRUUA=1
SLSRUA=0
SLSRUUA2=1
SLSRUA2=0
SLSSUUA=1
SLSSUA=0
SLSFUUA=1
SLSFUA=0

SNTLA=1
SNTLLUA=0
SNTLLA=1

;	Detailed

STGOUA=0
STGO=1
STGOUA2=1
STGO2=0
STGOUA3=1
STGO3=0
STGOUA4=1
STGO4=0
STGOUA5=1
STGO5=0

;	Statistics Disks

D2A=0
D2Y=10r
D2Y2=16r
D2B=1
D2BA=0
D3A=1
D3Y=0r
D3Y2=0r
D3B=0
D3BA=1
D4A=1
D4Y=0r
D4Y2=0r
D4B=0
D4BA=1
D5A=1
D5Y=0r
D5Y2=0r
D5B=0
D5BA=1
D6A=1
D6Y=0r
D6Y2=0r
D6B=0
D6BA=1
D7A=1
D7Y=0r
D7Y2=0r
D7B=0
D7BA=1
D8A=1
D8Y=0r
D8Y2=0r
D8B=0
D8BA=1
D9A=1
D9Y=0r
D9Y2=0r
D9B=0
D9BA=1
D10A=1
D10Y=0r
D10Y2=0r
D10B=0
D10BA=1

;	Dock

ISB=1
ISBUA=0
ISB2=1
ISBUA2=0
ISB3=1
ISBUA3=0
ISB4=1
ISBUA4=0
ISB5=0
ISBUA5=1

;	TaskbarX

TV=1
TVUA=0
TV2=0
TVUA2=1
TV3=1
TVUA3=0
TV4=1
TVUA4=0
TV5=1
TVUA5=0

TPUA=0
TP=1
TCUA=0
TC=1
TTIUA=0
TTI=1
TS=1
TSUA=0

;	TaskbarX

Chosen-Animation=backeaseout

TXGUA=0
TXG=1
TXGUA2=0
TXG2=1
TXGUA3=0
TXG3=1
TXGUA4=1
TXG4=0
TXGUA5=0
TXG5=1

;	Elegant Clock

CTO=0
CTOUA=1
CTO2=1
CTOUA2=0

CPO=0
CPOUA=1
CPO2=0
CPOUA2=1

;	VectorCopy

SVCTUA=1
SVCTA=0
SVCTUA2=0
SVCTA2=1

SVCCTUA=1
SVCCTA=0
SVCCTUA2=0
SVCCTA2=1

SVCSUA=0
SVCSA=1
SVCSUA2=1
SVCSA2=0
SVCSUA3=0
SVCSA3=1

SVCAUA1=0
SVCA1=1
SVCAUA2=0
SVCA2=1
SVCAUA3=0
SVCA3=1
SVCAUA4=0
SVCA4=1
SVCAUA5=0
SVCA5=1
SVCAUA6=0
SVCA6=1
SVCAUA7=0
SVCA7=1
SVCAUA8=0
SVCA8=1
SVCAUA9=1
SVCA9=0

SVCCTVUA=1
SVCCTVA=0
SVCCTVUA2=0
SVCCTVA2=1
SVCCTVUA3=0
SVCCTVA3=1
SVCCTVUA4=0
SVCCTVA4=1
SVCCTVUA5=0
SVCCTVA5=1

SVCIUA=0
SVCIA=1
SVCIUA2=1
SVCIA2=0

VisualizerType=Bar
VisualizerColorType=Custome
VisualizerScale=1
VisualizerHeight=300
VisualizerWidth=1680
VisualizerAlpha=255
VisualizerChameleonType=Foreground1
VisualizerBarWidth=16.7
VisualizerBarSpacing=10
VisualizerBarRoundess=0
VisualizerInverted=No
VisualizerSpacing=10
VisualizerAngle=0

;------------
;	Statistics
;------------

;	Maximal Download/Upload speed

MaxDownload=10000000
MaxUpload=10000000

;	Ping Host

Host=8.8.8.8

;	Net Total Limit

NetTotalLimit=200000

;	Maxilam GPu Memory

GPUMemMax=3072

;	Measures Engine

StatisticsMeasureEngine=msiafterburner

;	Logging

StatisticsLogging=1
StatisticsLoggingDelay=600
STLGUA=0
STLGO=1

;	Disk Letters

Disk1=#Disk-Letter#:
Disk2=#Disk-Letter2#:
Disk3=#Disk-Letter3#:
Disk4=#Disk-Letter4#:
Disk5=#Disk-Letter5#:
Disk6=#Disk-Letter6#:
Disk7=#Disk-Letter7#:
Disk8=#Disk-Letter8#:
Disk9=#Disk-Letter9#:
Disk10=#Disk-Letter10#:

;	Combined Includes

Import-Network=network-combined
Import-Disks=disks-combined
Import-System=system-combined

;	Network

SNL=0
SNLY=10r
SNLB=16r
SNU=0
SNUY=10r
SNUB=16r
SND=0
SNDY=10r
SNDB=16r
SNS=0
SNSY=10r
SNSB=16r
SNT=0
SNTY=10r
SNTB=16r

;	System

SLSCU=0
SLSCUY=10r
SLSCUB=16r
SLSCC=0
SLSCCY=10r
SLSCCB=16r
SLSCT=0
SLSCTY=10r
SLSCTB=16r
SLSGU=0
SLSGUY=10r
SLSGUB=16r
SLSGC=0
SLSGCY=10r
SLSGCB=16r
SLSGMC=0
SLSGMCY=10r
SLSGMCB=16r
SLSGMC2=0
SLSGMCY2=10r
SLSGMCB2=16r
SLSGMC3=0
SLSGMCY3=10r
SLSGMCB3=16r
SLSGV=0
SLSGVY=10r
SLSGVB=16r
SLSGT=0
SLSGTY=10r
SLSGTB=16r
SLSGFS=0
SLSGFSY=10r
SLSGFSB=16r
SLSGFS2=0
SLSGFSY2=10r
SLSGFSB2=16r
SLSRU=0
SLSRUY=10r
SLSRUB=16r
SLSRU2=0
SLSRUY2=10r
SLSRUB2=16r
SLSSU=0
SLSSUY=10r
SLSSUB=16r
SLSFU=0
SLSFUY=10r
SLSFUB=16r
SSVO=1
SSVOUA=0
SSVO2=0
SSVOUA2=1

;	Disks

Disk-Letter=C
Disk-Letter2=D
Disk-Letter3=E
Disk-Letter4=F
Disk-Letter5=G
Disk-Letter6=H
Disk-Letter7=I
Disk-Letter8=J
Disk-Letter9=K
Disk-Letter10=L

Disks-Combined-Path=disks-type

;	Detailed

SDDHG=1
SDPHG=1
SDGHG=1
SDMHG=1
SDNHG=1

D2DY=105r
D2DY2=15r
D2DY3=8r
D2DYY4=-5r
D2DY4=20r
D2DY5=-105r

D2DYY0=0r
D2DY0=105r
D2DY01=15r
D2DY02=8r
D2DY03=20r
D2DY04=-105r

DPGY=0
DMGY=0
DMGYY=80r
DNGY=0
DNGYY=165r
NDLY=180r
DGGY=-90r
DGGY2=145r
DGGY03=0
DGGY203=165r
DGGY04=0

;------------
;	Processes
;------------

HideGraph=0
GraphY=16r

TopProcessActive=gpu-process

;------------
;	Dock
;------------

DI2=35r
DIH2=0
DI3=35r
DIH3=0
DI4=35r
DIH4=0
DI5=35r
DIH5=0
DIW=228

Dock-Icon-1=new
Dock-Exe-1=Input program path here
Dock-Icon-2=new
Dock-Exe-2=Input program path here
Dock-Icon-3=new
Dock-Exe-3=Input program path here
Dock-Icon-4=new
Dock-Exe-4=Input program path here
Dock-Icon-5=new
Dock-Exe-5=Input program path here
Dock-Icon-6=new
Dock-Exe-6=Input program path here
DI=35r
DHI=0

;------------
;	Elegant Clock
;------------

TMA=0
TMA2=1

;	Date Info

CDIA=0
CDIY=35r

;	Year Info

CYIA=0
CYIY=15r

Date-Format=en-US
Time-Format=local

;------------
;	CyberSearch
;------------

Engine-Icon=google
Engine-URL-Query=https://www.google.com/search?q={q}
Engine-Name=Google

CSEUA=1
CSE=0
CSEUA2=0
CSE2=1
CSEUA3=0
CSE3=1
CSEUA4=0
CSE4=1
CSEUA5=0
CSE5=1

;------------
;	Translucent Taskbar
;------------

TTAS=

;------------
;	TaskbarX
;------------

TaskbarXR=0
TaskbarXG=0
TaskbarXB=0
TaskbarXAlpha=40
TaskbarXAnimation=backeaseout

;	Animation Style

as=#TaskbarXAnimation#
obas=#TaskbarXAnimation#

;	Variation

tbs=2

;	Pause

cfsa=0

;	Centering

cso=0

;	Tray-Icon

sti=0

;	Color

color=#TaskbarXR#;#TaskbarXG#;#TaskbarXB#;#TaskbarXAlpha#

;	Segments

tbsg=0

;	Other

ptbo=0
stbo=0
cpo=0
dct=0
asp=300
lr=400
oblr=400
cib=0
ftotc=1
sr=500
sr2=500
sr3=500
hps=0
hss=0
hpt=0
dtbsowm=0
tpop=100
tsop=100
hst=0
rzbt=1
tbr=0

;------------
;	Quality
;------------

AntiAliasingPM=1
StringEffectPM=Shadow
StringStylePM=Bold
VisualizerSmoothing=Exponential

;------------
;	Background Panel
;------------

BackgroundTrayIcon=1
BackgroundNotyfications=1

;	Please report to me any variable which is under this one
---------BUGS------=NULL
