;	This file containts all styles

[Variables]

;------------
;	Styles
;------------

;	Headers

[H1]
StringCase=Upper
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,50
FontColor=#PrimaryColor#
FontFace=#PanelFont#
FontSize=15

AntiAlias=#AntiAliasingPM#
ClipString=1

[H2]
StringCase=Upper
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,50
FontColor=#TertiaryColor#
FontFace=#PanelFont#
FontSize=14

AntiAlias=#AntiAliasingPM#
ClipString=1

[H3]
StringCase=Upper
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,50
FontColor=#TertiaryColor#
FontFace=#PanelFont#
FontSize=10

AntiAlias=#AntiAliasingPM#
ClipString=1

[H4]
StringAlign=Center
StringCase=Upper
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,50
FontColor=#IPrimaryColor#
FontFace=#IllustroFont#
FontSize=10

AntiAlias=#AntiAliasingPM#
ClipString=1

;	Texts

[TEXT]
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#QuaternaryColor#
FontFace=#PanelFont#
FontSize=12

AntiAlias=#AntiAliasingPM#
ClipString=1

[LEFT-ALIGN]
StringAlign=Left
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#ISecondaryColor#
FontFace=#IllustroFont#
FontSize=8

AntiAlias=#AntiAliasingPM#
ClipString=1

[RIGHT-ALIGN]
StringAlign=Right
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#ITertiaryColor#
FontFace=#IllustroFont#
FontSize=8

AntiAlias=#AntiAliasingPM#
ClipString=1
Padding=0,0,3,0

[CENTER-ALIGN]
StringAlign=Center
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#ITertiaryColor#
FontFace=#IllustroFont#
FontSize=8

AntiAlias=#AntiAliasingPM#
ClipString=1

[DESCRIPTION]
StringCase=None
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#SecondaryColor#
FontFace=#PanelFont#
FontSize=10

AntiAlias=#AntiAliasingPM#
ClipString=1

;	Special

[BUTTONS]
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#SenaryColor#
FontFace=#PanelFont#
SolidColor=200,200,200,40
FontSize=10

AntiAlias=#AntiAliasingPM#
ClipString=1

[SIDEBAR]
StringAlign=Right
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#SeptenaryColor#
FontFace=#PanelFont#
FontSize=12

AntiAlias=#AntiAliasingPM#
ClipString=1
SolidColor=0,0,0,1

[LINKS-BAR]
FontSize=12
StringCase=None
StringStyle=#StringStylePM#
StringEffect=#StringEffectPM#

FontEffectColor=0,0,0,20
FontColor=#QuinaryColor#
FontFace=#PanelFont#

AntiAlias=#AntiAliasingPM#
ClipString=1
DynamicVariables=1
X=20r
Y=0r

[BAR]
BarColor=#IQuaternaryColor#
BarOrientation=HORIZONTAL
SolidColor=255,255,255,15

[CORE-BAR]
BarColor=#IQuaternaryColor#
BarOrientation=VERTICAL

[GRAPH]
W=191
H=39
AutoScale=1
AntiAlias=#AntiAliasingPM#
LineColor=#ISenaryColor#
LineColor2=255,255,255,255
LineColor3=0,255,0,255
LineWidth=1
LineCount=1
GraphStart=Right

[SEPERATOR]
SolidColor=#ISeptenaryColor#,50