[Variables]

;------------
;	Global
;------------

MainLanguage=#@#\Addons\Languages\EN.inc
PanelFont=Trebuchet MS
IllustroFont=Bahnschrift
NotificationsContent=closetray
ErrorCode=100

;	Version of the bundle

Version=1.0.9

;	Multiple bangs combined into one variable

Refreshes=[!RefreshGroup "Ashuramaru-Bundle Group"][!RefreshGroup "Ashuramaru-Bundle Statistics"][!RefreshGroup "Ashuramaru-Bundle Clock"][!RefreshGroup "Ashuramaru-Bundle Top-Processes"][!RefreshGroup "Ashuramaru-Bundle CyberSearch"][!RefreshGroup "Ashuramaru-Bundle Dock"][!RefreshGroup "Ashuramaru-Bundle Dock-Single"][!RefreshGroup "Ashuramaru-Bundle-Visualizers-Group"][!RefreshGroup "Ashuramaru-Bundle Setup"][!RefreshGroup "Ashuramaru-Bundle Statistics-Detailed"][!RefreshGroup "ColorPicker"]

Deactivates=[!DeactivateConfigGroup "Ashuramaru-Bundle Group"][!DeactivateConfigGroup "Ashuramaru-Bundle Statistics"][!DeactivateConfigGroup "Ashuramaru-Bundle Clock"][!DeactivateConfigGroup "Ashuramaru-Bundle Top-Processes"][!DeactivateConfigGroup "Ashuramaru-Bundle CyberSearch"][!DeactivateConfigGroup "Ashuramaru-Bundle Dock"][!DeactivateConfigGroup "Ashuramaru-Bundle Dock-Single"][!DeactivateConfigGroup "Ashuramaru-Bundle-Visualizers-Group"][!DeactivateConfigGroup "Ashuramaru-Bundle Setup"][!DeactivateConfigGroup "Ashuramaru-Bundle Statistics-Detailed"]

;	Frost Glass Plugin

OpaqueBG=None

;------------
;	Panel
;------------

PageName=Welcome
PageActive=
PageActive2=>
PageActive3=
PageActive4=
PageActive5=

State-Taskbar=1
State-TaskbarX=0
State-VectorCopy=0
State-Clock=0
State-Battery=1
State-Recycle-Bin=1
State-Hardware-Info=1
State-Dock=1
State-CyberSearch=1
State-Notes=1
State-Volume-Control=1
State-System-Control=1
State-Clipboard=1

;	Appearance

Background-Image=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Images\Backgrounds\Solid.png
Background-Image-Blank=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Images\Backgrounds\Solid-Blank.png
Background-Image-Header=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Images\Backgrounds\Solid-Header.png
Background-Image-Header-Top=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Images\Backgrounds\Solid-Header.png

Modern=#@#\Images\Backgrounds\Modern.png
Classic=#@#\Images\Backgrounds\Classic.png
Rounded=#@#\Images\Backgrounds\Rounded.png
Opaque=#@#\Images\Backgrounds\Opaque.png
Definitive=#@#\Images\Backgrounds\Definitive.png
Light=#@#\Images\Backgrounds\Light.png
Solid=#@#\Images\Backgrounds\Solid.png
Modern-Blank=#@#\Images\Backgrounds\Modern-Blank.png
Classic-Blank=#@#\Images\Backgrounds\Classic-Blank.png
Rounded-Blank=#@#\Images\Backgrounds\Rounded-Blank.png
Opaque-Blank=#@#\Images\Backgrounds\Opaque-Blank.png
Definitive-Blank=#@#\Images\Backgrounds\Definitive-Blank.png
Light-Blank=#@#\Images\Backgrounds\Light-Blank.png
Solid-Blank=#@#\Images\Backgrounds\Solid-Blank.png
Modern-Header=#@#\Images\Backgrounds\Modern-Header.png
Classic-Header=#@#\Images\Backgrounds\Classic-Header.png
Rounded-Header=#@#\Images\Backgrounds\Rounded-Header.png
Opaque-Header=#@#\Images\Backgrounds\Opaque-Header.png
Definitive-Header=#@#\Images\Backgrounds\Definitive-Header.png
Light-Header=#@#\Images\Backgrounds\Light-Header.png
Solid-Header=#@#\Images\Backgrounds\Solid-Header.png
Classic-Header-Top=#@#\Images\Backgrounds\Classic-Header-Top.png
Modern-Header-Top=#@#\Images\Backgrounds\Modern-Header.png
Rounded-Header-Top=#@#\Images\Backgrounds\Rounded-Header.png
Opaque-Header-Top=#@#\Images\Backgrounds\Opaque-Header.png
Definitive-Header-Top=#@#\Images\Backgrounds\Definitive-Header.png
Light-Header-Top=#@#\Images\Backgrounds\Light-Header.png
Solid-Header-Top=#@#\Images\Backgrounds\Solid-Header.png

SystemIcon=NONE

BTOUA=0
BTO=1
BTOUA2=0
BTO2=1
BTOUA3=0
BTO3=1
BTOUA4=0
BTO4=1
BTOUA5=0
BTO5=1
BTOUA6=0
BTO6=1
BTOUA7=0
BTO7=1
BTOUA8=0
BTO8=1
BTOUA9=1
BTO9=0

ASIUA=0
ASI=1
ASIUA2=0
ASI2=1
ASIUA3=0
ASI3=1
ASIUA4=1
ASI4=0

;	FontChanger

Font-To-Change=NULL
FontChangerVAR=NULL
fontslistpage=fontslist

FCPFUA=0
FCPF=1
FCIFUA=0
FCIF=1

;	ColorPicker

Color-To-Paint=OSecondaryColor

;	Panel Colors

PrimaryColor=255,0,0
SecondaryColor=255,255,255
TertiaryColor=255,255,255
QuaternaryColor=255,255,255
QuinaryColor=255,0,0
SenaryColor=255,255,255
SeptenaryColor=255,255,255

;	Illustro Collors

IPrimaryColor=255,255,255
ISecondaryColor=255,255,255
ITertiaryColor=255,255,255
IQuaternaryColor=255,0,0
IQuinaryColor=255,0,0
ISenaryColor=255,0,0
ISeptenaryColor=255,255,255

;	Other Colors

OPrimaryColor=255,0,0
OSecondaryColor=

;	Presets Activation

Preset-1-No-Active=0
Preset-1-Is-Active=1
Preset-2-No-Active=0
Preset-2-Is-Active=1

;	Presets Saved Color

PresetSaved-Primary=255,0,0
PresetSaved-Secondary=255,255,255
PresetSaved-Tertiary=255,255,255
PresetSaved-Quaternary=255,255,255
PresetSaved-Quinary=255,0,0
PresetSaved-Senary=255,255,255
PresetSaved-Septenary=255,255,255
PresetSaved-IPrimary=255,255,255
PresetSaved-ISecondary=255,255,255
PresetSaved-ITertiary=255,255,255
PresetSaved-IQuaternary=255,0,0
PresetSaved-IQuinary=255,0,0
PresetSaved-ISenary=255,0,0
PresetSaved-ISeptenary=255,255,255
PresetSaved-OPrimary=255,0,0
PresetSaved-OSecondary=

;	Preset 1

Preset1-Primary=99,0,188
Preset1-Secondary=255,255,255
Preset1-Tertiary=255,255,255
Preset1-Quaternary=255,255,255
Preset1-Quinary=99,0,188
Preset1-Senary=255,255,255
Preset1-Septenary=255,255,255
Preset1-IPrimary=255,255,255
Preset1-ISecondary=255,255,255
Preset1-ITertiary=255,255,255
Preset1-IQuaternary=99,0,188
Preset1-IQuinary=99,0,188
Preset1-ISenary=99,0,188
Preset1-ISeptenary=255,255,255
Preset1-OPrimary=99,0,188
Preset1-OSecondary=

;	Preset 2

Preset2-Primary=255,0,0
Preset2-Secondary=0,0,0
Preset2-Tertiary=0,0,0
Preset2-Quaternary=0,0,0
Preset2-Quinary=255,0,0
Preset2-Senary=0,0,0
Preset2-Septenary=0,0,0
Preset2-IPrimary=0,0,0
Preset2-ISecondary=0,0,0
Preset2-ITertiary=0,0,0
Preset2-IQuaternary=255,0,0
Preset2-IQuinary=255,0,0
Preset2-ISenary=255,0,0
Preset2-ISeptenary=0,0,0
Preset2-OPrimary=255,0,0
Preset2-OSecondary=

;------------
;	Panel - Settings
;------------

;	Panel

TOUA=1
TO=0

PMON=1
PMOFF=0

GMO=1
GMOFF=0
NFOFF=1
NFMO=0
LOFF=0
LON=1

GMO1UA=0
GMO1=1
GMO2UA=0
GMO2=1
GMO3UA=0
GMO3=1
GMO4UA=0
GMO4=1
GMO5UA=0
GMO5=1
GMO6UA=0
GMO6=1
GMO7UA=0
GMO7=1
GMO8UA=0
GMO8=1

QOUA=0
QOUAG=1
QOA=1
QOUA2=0
QOUAG2=1
QOA2=1
QOUA3=1
QOUAG3=1
QOA3=0

;	Statistics

LO=0
LOUA=1
LO2=1
LOUA2=0

TTVO=0
TTVOUA=1
TTVO2=1
TTVOUA2=0

VVO=1
VVOUA=0
VVO2=1
VVOUA2=0
VVO3=1
VVOUA3=0
VVO4=1
VVOUA4=0

SCTOO=0
SCTOY=3r
SCTOYY=10r
SCTOO2=0
SCTOY2=3r
SCTOYY2=10r

SMEUA=1
SMEA=0
SMEUA2=0
SMEA2=1

SDTUA=0
SDTA=1
SDTUA2=1
SDTA2=0

;	Processes

PVO=1
PVOUA=0
PVO2=1
PVOUA2=0

PGOUA=1
PGOA=0

;	Variations

SVO=0
SVOUA1=1
SVO2=1
SVOUA2=0
SVO3=1
SVOUA3=0

SVA=1
SVA2=1
SVA3=0

SVT=0
SVTUA=1
SVT2=0
SVTUA2=1
SVT3=1
SVTUA3=1
SVT4=0
SVTUA4=1

SGA=1
SGA2=1
SGA3=1
SGA4=1
SGA5=1
SGUA=0
SGUA2=0
SGUA3=0
SGUA4=0
SGUA5=0

SDL=1
SDL2=1
SDL3=1
SDL4=0
SDL5=1
SDL6=0
SDL7=0
SDL8=0
SDL9=0

SDLUA=0
SDLUA2=0
SDLUA3=0
SDLUA4=1
SDLUA5=0
SDLUA6=1
SDLUA7=1
SDLUA8=1
SDLUA9=1

SLNUUA=1
SLNUA=0
SLNDUA=1
SLNDA=0
SLNTUA=1
SLNTA=0
SLNSUA=1
SLNSA=0

SLSCCUA=0
SLSCCA=1
SLSCTUA=1
SLSCTA=0
SLSGUUA=1
SLSGUA=0
SLSGCUA=0
SLSGCA=1
SLSGMCUA=0
SLSGMCA=1
SLSGMCUA2=1
SLSGMCA2=0
SLSGMCUA3=0
SLSGMCA3=1
SLSGVUA=0
SLSGVA=1
SLSGTUA=1
SLSGTA=0
SLSGFSUA=1
SLSGFSA2=1
SLSGFSUA2=0
SLSGFSA=0
SLSRUUA=1
SLSRUA=0
SLSSUUA=1
SLSSUA=0

SNTLA=0
SNTLLUA=1
SNTLLA=0

;	Detailed

STGOUA=1
STGO=0
STGOUA2=1
STGO2=0
STGOUA3=1
STGO3=0
STGOUA4=1
STGO4=0
STGOUA5=1
STGO5=0

;	Statistics Disks

D2A=0
D2Y=10r
D2Y2=16r
D2B=1
D2BA=0
D3A=0
D3Y=10r
D3Y2=16r
D3B=1
D3BA=0
D4A=0
D4Y=10r
D4Y2=16r
D4B=1
D4BA=0
D5A=1
D5Y=0r
D5Y2=0r
D5B=0
D5BA=1
D6A=0
D6Y=10r
D6Y2=16r
D6B=1
D6BA=0
D7A=1
D7Y=0r
D7Y2=0r
D7B=0
D7BA=1
D8A=1
D8Y=0r
D8Y2=0r
D8B=0
D8BA=1
D9A=1
D9Y=0r
D9Y2=0r
D9B=0
D9BA=1
D10A=1
D10Y=0r
D10Y2=0r
D10B=0
D10BA=1

;	Dock

ISB=1
ISBUA=0
ISB2=1
ISBUA2=0
ISB3=1
ISBUA3=0
ISB4=1
ISBUA4=0
ISB5=0
ISBUA5=1

;	TaskbarX

TV=1
TVUA=0
TV2=0
TVUA2=1
TV3=1
TVUA3=0
TV4=1
TVUA4=0
TV5=1
TVUA5=0

TPUA=0
TP=1
TCUA=0
TC=1
TTIUA=0
TTI=1
TS=1
TSUA=0

;	TaskbarX

Chosen-Animation=backeaseout

TXGUA=0
TXG=1
TXGUA2=0
TXG2=1
TXGUA3=0
TXG3=1
TXGUA4=1
TXG4=0
TXGUA5=0
TXG5=1

;	Clock

CTO=0
CTOUA=1
CTO2=1
CTOUA2=0

CPO=0
CPOUA=1
CPO2=0
CPOUA2=1

;------------
;	Statistics
;------------

MaxDownload=10000000
MaxUpload=10000000
Host=8.8.8.8
NetTotalLimit=200000
GPUMemMax=3072
StatisticsMeasureEngine=msiafterburner

Disk1=#Disk-Letter#:
Disk2=#Disk-Letter2#:
Disk3=#Disk-Letter3#:
Disk4=#Disk-Letter4#:
Disk5=#Disk-Letter5#:
Disk6=#Disk-Letter6#:
Disk7=#Disk-Letter7#:
Disk8=#Disk-Letter8#:
Disk9=#Disk-Letter9#:
Disk10=#Disk-Letter10#:

Import-Network=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Addons\Statistics\network-combined.inc
Import-Disks=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Addons\Statistics\disks-combined.inc
Import-System=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Addons\Statistics\system-combined.inc

;	Network

SNU=0
SNUY=10r
SNUB=16r
SND=0
SNDY=10r
SNDB=16r
SNS=0
SNSY=10r
SNSB=16r
SNT=0
SNTY=10r
SNTB=16r

;	System

SLSCC=1
SLSCCY=0r
SLSCCB=0r
SLSCT=0
SLSCTY=10r
SLSCTB=16r
SLSGU=0
SLSGUY=10r
SLSGUB=16r
SLSGC=1
SLSGCY=0r
SLSGCB=0r
SLSGMC=1
SLSGMCY=0r
SLSGMCB=0r
SLSGMC2=0
SLSGMCY2=10r
SLSGMCB2=16r
SLSGMC3=1
SLSGMCY3=0r
SLSGMCB3=0r
SLSGV=1
SLSGVY=0r
SLSGVB=0r
SLSGT=0
SLSGTY=10r
SLSGTB=16r
SLSGFS=0
SLSGFSY=10r
SLSGFSB=16r
SLSGFS2=1
SLSGFSY2=0r
SLSGFSB2=0r
SLSRU=0
SLSRUY=10r
SLSRUB=16r
SLSSU=0
SLSSUY=10r
SLSSUB=16r

SSVO=1
SSVOUA=0
SSVO2=0
SSVOUA2=1

;	Disks

Disk-Letter=C
Disk-Letter2=D
Disk-Letter3=E
Disk-Letter4=F
Disk-Letter5=G
Disk-Letter6=H
Disk-Letter7=I
Disk-Letter8=J
Disk-Letter9=K
Disk-Letter10=L

Disks-Combined-Path=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Addons\Statistics\disks-type2.inc

;	Detailed

SDDHG=0
SDPHG=0
SDGHG=0
SDMHG=0
SDNHG=0

D2DY=50r
D2DY2=15r
D2DY3=8r
D2DYY4=50r
D2DY4=20r
D2DY5=1r

D2DYY0=50r
D2DY0=50r
D2DY01=15r
D2DY02=8r
D2DY03=20r
D2DY04=1r

DPGY=20r
DMGY=20r
DMGYY=50r
DNGY=20r
DNGYY=50r
NDLY=50r
DGGY=20r
DGGY2=50r
DGGY03=20r
DGGY203=50r
DGGY04=20r

;------------
;	Processes
;------------

HideGraph=0
GraphY=16r

TopProcessCPU=#@#\Addons\TopProcess\cpu-process.inc
TopProcessGPU=#@#\Addons\TopProcess\gpu-process.inc
TopProcessRAM=#@#\Addons\TopProcess\ram-process.inc
TopProcessIO=#@#\Addons\TopProcess\io-process.inc

TopProcessActive=#TopProcessCPU#

;------------
;	Dock
;------------

DI2=35r
DIH2=0
DI3=35r
DIH3=0
DI4=35r
DIH4=0
DI5=35r
DIH5=0
DIW=228

Dock-Icon-1=new
Dock-Exe-1=NOT DEFINED
Dock-Icon-2=new
Dock-Exe-2=NOT DEFINED
Dock-Icon-3=new
Dock-Exe-3=NOT DEFINED
Dock-Icon-4=new
Dock-Exe-4=NOT DEFINED
Dock-Icon-5=new
Dock-Exe-5=NOT DEFINED
Dock-Icon-6=new
Dock-Exe-6=NOT DEFINED
DI=35r
DHI=0

;------------
;	Clock
;------------

TMA=0
TMA2=1

;	Date Info

CDIA=0
CDIY=35r

;	Year Info

CYIA=0
CYIY=15r

Date-Format=en-US
Time-Format=local

;------------
;	CyberSearch
;------------

Engine-Icon=C:\Users\shado\Documents\Rainmeter\Skins\Ashuramaru-Bundle\@Resources\\Images\Icons\SearchEngines\google.png
Engine-URL-Query=https://www.google.com/search?q={q}
Engine-Name=Google

CSEUA=1
CSE=0
CSEUA2=0
CSE2=1
CSEUA3=0
CSE3=1
CSEUA4=0
CSE4=1
CSEUA5=0
CSE5=1

;------------
;	Translucent Taskbar
;------------

TTAS=2

;------------
;	TaskbarX
;------------

;	Animation Style

as=backeaseout
obas=backeaseout

;	Variation

tbs=2

;	Pause

cfsa=0

;	Centering

cso=0

;	Tray-Icon

sti=0

;	Color

color=0;0;0;40

;	Segments

tbsg=0

;	Other

ptbo=0
stbo=0
cpo=0
dct=0
asp=300
lr=400
oblr=400
cib=0
ftotc=1
sr=500
sr2=500
sr3=500
hps=0
hss=0
hpt=0
dtbsowm=0
tpop=100
tsop=100
hst=0
rzbt=1
tbr=0

;------------
;	Game Mode
;------------

GMTaskbarX=
GMTaskbar=
GMClock=
GMBattery=
GMRecycleBin=
GMDock=
GMNotes=
GMCyberSearch=

;------------
;	Performance Monitor
;------------

AntiAliasingPM=1
StringEffectPM=Shadow
StringStylePM=Bold

;	Please report to me any variable which is under this one
---------BUGS------=NULL
SDLU9=0
